apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mytest1
  name: mytest1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mytest1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mytest1
    spec:
      containers:
      - image: ubuntu
        name: nginx
        command: ["sleep","3600"]
        resources: {}
status: {}
