apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprodb
  namespace: default
  labels:
    app: vprodb
spec:
  selector:
    matchLabels:
      app: vprodb
  replicas: 1
  template:
    metadata:
      labels:
        app: vprodb
    spec:
      # initContainers:
      # Init containers are exactly like regular containers, except:
      # - Init containers always run to completion.
      # - Each init container must complete successfully before the next one starts.
      containers:
        - name: vprodb
          image: vprofile/vprofiledb:V1
          args:
            - "--ignore-db-dir=lost+found"
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: db-pass
          ports:
            - containerPort: 3306
              name: vprodb-port
          volumeMounts:
            - name: vpro-db-data
              mountPath: /var/lib/mysql
      nodeSelector:
        zone: ap-south-1a
      volumes:
        - name: vpro-db-data
          awsElasticBlockStore:
            volumeID: vol-0b4bbc76505e9d053
            fsType: ext4
      restartPolicy: Always
