apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpromc
  namespace: default
  labels:
    app: vpromc
spec:
  selector:
    matchLabels:
      app: vpromc
  replicas: 1

  template:
    metadata:
      labels:
        app: vpromc
    spec:
      # initContainers:
      # Init containers are exactly like regular containers, except:
      # - Init containers always run to completion.
      # - Each init container must complete successfully before the next one starts.
      containers:
        - name: vpromc
          image: memcached
          ports:
            - containerPort: 11211
              name: vpromc-port

      restartPolicy: Always
