apiVersion: v1
kind: Service
metadata:
  name: vprocache01
  namespace: default
spec:
  selector:
    app: vpromc
  type: ClusterIP
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
    - name: vprocache01
      protocol: TCP
      port: 11211
      targetPort: vpromc-port
