apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpromq01
  namespace: default
  labels:
    app: vpromq01
spec:
  selector:
    matchLabels:
      app: vpromq01
  replicas: 1

  template:
    metadata:
      labels:
        app: vpromq01
    spec:
      # initContainers:
      # Init containers are exactly like regular containers, except:
      # - Init containers always run to completion.
      # - Each init container must complete successfully before the next one starts.
      containers:
        - name: vpromq01
          image: rabbitmq

          ports:
            - containerPort: 15672
              name: vpromq-port
          env:
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  key: rm-pass
                  name: app-secret
            - name: RABBITMQ_DEFAULT_USER
              value: "guest"
      restartPolicy: Always
