apiVersion: v1
kind: PersistentVolume
metadata:
  name: vpro-db-data

spec:
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    fsType: xfs
    volumeID: aws://ap-south-1a/vol-03799cad81454e762
    partition: 1
  capacity:
    storage: 3Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp2-retain
  volumeMode: Filesystem
