apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: vprodb
  name: vpro-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: gp2-retain
  volumeMode: Filesystem
  volumeName: vpro-db-data
