apiVersion: v1
kind: Service
metadata:
  name: vproapp-service
  namespace: default
spec:
  selector:
    app: vproapp
  type: LoadBalancer
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
    - name: vproapp-service
      protocol: TCP
      port: 80
      targetPort: vproapp-port
