apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: vprodb
  name: vpro-db-pvc
  namespace: testy
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: default
  volumeMode: Filesystem
  volumeName: vprodb-pv
