pipeline {
  agent 'Master'
  
  stages {
    
     stage('Git Checkout') {
            steps {
                checkout([
                    $class: 'GitSCM', 
                    branches: [[name: 'master']], 
                    userRemoteConfigs: [[url: 'git@github.com:OpMilan29/myapp.git']]
                ])
            }
        }
    stage('Docker build') {
      steps {
        sh  ''' 
        docker 
        '''
        }
    }
  }
}
        
        
