pipeline {
  
   agent any
  
  stages {
    
     stage('Git Checkout') {
       agent any
            steps {
                sh '''
                
                echo "stage 1"
                sleep 20
                
                '''
             
            }
        }
    stage('Docker build') {
      agent any
      steps {
        sh  ''' 
        docker --version
        pwd
        sleep 20
        '''
        }
    }
  }
}
        
        
