pipeline {
  
   agent any
  
  stages {
    
     stage('Git Checkout') {
       agent any
            steps {
                checkout([
                    $class: 'GitSCM', 
                    branches: [[name: 'master']], 
                    userRemoteConfigs: [[url: 'git@github.com:OpMilan29/myapp.git']]
                ])
            }
        }
    stage('Docker build') {
      agent any
      steps {
        sh  ''' 
        docker --version
        pwd
        sleep 20
        '''
        }
    }
  }
}
        
        
